import 'package:freezed_annotation/freezed_annotation.dart';

part 'subtitle_info.freezed.dart';
part 'subtitle_info.g.dart';

@freezed
class SubtitleInfo with _$SubtitleInfo {
  const factory SubtitleInfo({
    required String languageCode,
    required String languageName,
    required String url,
    @Default(false) bool isAutoGenerated,
  }) = _SubtitleInfo;

  factory SubtitleInfo.fromJson(Map<String, dynamic> json) =>
      _$SubtitleInfoFromJson(json);
}
