// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_youtube_downloader/test/domain/usecases/analyze_video_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_youtube_downloader/core/error/failures.dart' as _i5;
import 'package:flutter_youtube_downloader/domain/entities/playlist_info.dart'
    as _i7;
import 'package:flutter_youtube_downloader/domain/entities/video_info.dart'
    as _i6;
import 'package:flutter_youtube_downloader/domain/repositories/video_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VideoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoRepository extends _i1.Mock implements _i3.VideoRepository {
  MockVideoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.VideoInfo>> analyzeVideo(
    String? url,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeVideo, [url]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.VideoInfo>>.value(
                  _FakeEither_0<_i5.Failure, _i6.VideoInfo>(
                    this,
                    Invocation.method(#analyzeVideo, [url]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.VideoInfo>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> validateUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#validateUrl, [url]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#validateUrl, [url]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.PlaylistInfo>> getPlaylistInfo(
    String? url,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistInfo, [url]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.PlaylistInfo>>.value(
                  _FakeEither_0<_i5.Failure, _i7.PlaylistInfo>(
                    this,
                    Invocation.method(#getPlaylistInfo, [url]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.PlaylistInfo>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#clearCache, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.VideoInfo?>> getCachedVideo(
    String? url,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedVideo, [url]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.VideoInfo?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.VideoInfo?>(
                    this,
                    Invocation.method(#getCachedVideo, [url]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.VideoInfo?>>);
}
